server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: App
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /menuSearches/**
        - id: Adress Check
          uri: http://localhost:8082
          predicates:
            - Path=/checkOederAdresses/**, 
        - id: Pay
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**, 
        - id: store
          uri: http://localhost:8084
          predicates:
            - Path=/foodCookings/**, 
        - id: Delivery
          uri: http://localhost:8085
          predicates:
            - Path=/deliveryOrderProcessings/**, 
        - id: Customer
          uri: http://localhost:8086
          predicates:
            - Path=, /orderstatuses/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: App
          uri: http://app:8080
          predicates:
            - Path=/orders/**, /menuSearches/**
        - id: Adress Check
          uri: http://adressCheck:8080
          predicates:
            - Path=/checkOederAdresses/**, 
        - id: Pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/foodCookings/**, 
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveryOrderProcessings/**, 
        - id: Customer
          uri: http://customer:8080
          predicates:
            - Path=, /orderstatuses/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
